spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: http://localhost:8081
          predicates:
            - Path=/student/**
        - id: department-service
          uri: http://localhost:8080
          predicates:
            - Path=/department/**
  config:
    import: "optional:configserver:http://localhost:8088"
            
  
    

        